ModernLibrary/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BookController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BerandaController;
use App\Http\Controllers\CategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('auth.login');
// });

Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    
    
});

Route::middleware(['auth', 'admin'])->group(function () {
    Route::resource('category', CategoryController::class);
    Route::resource('user', UserController::class);
    Route::resource('books', BookController::class);
    Route::get('tampil/{id}', [BookController::class, 'hide']);
});


Route::get('beranda', [HomeController::class, 'index']);
Route::get('/', [BerandaController::class, 'index']);
Route::post('beranda', [BerandaController::class, 'store']);
Route::post('updateloan', [BerandaController::class, 'update']);

ModernLibrary/resources/views/admin/category-add.blade.php
@extends('layouts.template')

@section('title', 'Tambah Kategori')

@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Data /</span> <span class="text-muted fw-light">Kelola Kategori /</span> Tambah Jenis Kategori</h4>
    <div class="col-xxl">
        <div class="card mb-4">
            <div class="card-header d-flex align-items-center justify-content-between">
                <h5 class="mb-0">Tambah Data Kategori</h5>
            </div>
            <div class="card-body">
                <form action="{{ route('category.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label" for="basic-icon-default-fullname">Jenis Kategori</label>
                        <div class="col-sm-10">
                            <div class="input-group input-group-merge">
                                <span id="basic-icon-default-fullname2" class="input-group-text"><i class='bx bxs-category-alt'></i></span>
                                <input type="text" class="form-control" name="nama_kategori" id="basic-icon-default-fullname"
                                     placeholder="Masukkan Kategori" aria-label="John Doe"
                                    aria-describedby="basic-icon-default-fullname2" />
                            </div>
                        </div>
                    </div>
                    <div class="row justify-content-end">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

ModernLibrary/resources/views/admin/category-edit.blade.php
@extends('layouts.template')

@section('title', 'Tambah Kategori')

@section('content')
<div class="container-xxl container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Data /</span> <span class="text-muted fw-light">Kelola Kategori /</span> Tambah Jenis Kategori</h4>
    <div class="col-xxl">
        <div class="card mb-4">
            <div class="card-header d-flex align-items-center justify-content-between">
                <h5 class="mb-0">Tambah Data Kategori</h5>
            </div>
            <div class="card-body">
                <form action="{{ route('category.update', $category->id) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label" for="basic-icon-default-fullname">Jenis Kategori</label>
                        <div class="col-sm-10">
                            <div class="input-group input-group-merge">
                                <span id="basic-icon-default-fullname2" class="input-group-text"><i class='bx bxs-category-alt'></i></span>
                                <input type="text" class="form-control" name="nama_kategori" value="{{ $category->nama_kategori }}" id="basic-icon-default-fullname"
                                     placeholder="Masukkan Kategori" aria-label="John Doe"
                                    aria-describedby="basic-icon-default-fullname2" />
                            </div>
                        </div>
                    </div>
                    <div class="row justify-content-end">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

ModernLibrary/resources/views/admin/category.blade.php
@extends('layouts.template')

@section('title', 'Data Kategori')
@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Data /</span> Kelola Kategori</h4>

    <!-- Basic Bootstrap Table -->
    <div class="card">
        <h5 class="card-header">Kelola Kategori Buku</h5>
        <div class="table-responsive">
            <a href="{{ route('category.create') }}" class="btn btn-primary ms-3">Tambah Data</a>
            <table class="table" id="myTable">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Kategori</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody class="table-border-bottom-0">
                    @foreach ($category as $item)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $item->nama_kategori }}</td>
                        <td>
                            <div class="dropdown">
                                <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown"><i class="bx bx-dots-vertical-rounded"></i></button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item btn btn-primary" href="{{ route('category.edit', $item->id) }}"><i class="bx bx-edit-alt me-1"></i>Edit</a>
                                    <form action="{{ route('category.destroy', $item -> id) }}" method="POST" id="myForm">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="dropdown-item btn btn-danger" onclick="return confirm('Yakin hapus Data ?')"><i class="bx bx-trash me-1"></i>Delete</button>
                                    </form>
                                </div>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>

@endsection