ModernLibrary/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BookController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BerandaController;
use App\Http\Controllers\CategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('auth.login');
// });

Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    
    
});

Route::middleware(['auth', 'admin'])->group(function () {
    Route::resource('category', CategoryController::class);
    Route::resource('user', UserController::class);
    Route::resource('books', BookController::class);
    Route::get('tampil/{id}', [BookController::class, 'hide']);
});


Route::get('beranda', [HomeController::class, 'index']);
Route::get('/', [BerandaController::class, 'index']);
Route::post('beranda', [BerandaController::class, 'store']);
Route::post('updateloan', [BerandaController::class, 'update']);

ModernLibrary/app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;

    protected $table = "books";
    protected $fillable = ["isbn", "judul_buku", "penerbit", "sinopsis", "keterangan", "cover", "stock", "tampil","category_id"];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

ModernLibrary/app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

// use App\Models\Book;
use App\Models\Book;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use RealRashid\SweetAlert\Facades\Alert;


class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $book = Book::all();
        $category = Category::all();

        return view('admin.books.tampil' ,compact('book', 'category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = Category::all();
        $book = Book::all();
        
        return view('admin.books.tambah',['category' => $category, 'book' =>$book] );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $validator = $request->validate([
            'isbn'=>'required',
            'judul_buku'=>'required',
            'penerbit'=>'required',
            'sinopsis'=>'required',
            'keterangan'=>'required',
            'cover' => 'required|image|max:10000|mimes:jpg',
            'stock'=>'required',
            'category_id' => 'required'

        ]);

        $newName = '';

        if($request->file('cover')){
            $extension = $request->file('cover')->getClientOriginalExtension();
            $newName = $request->judul.'-'.now()->timestamp.'.'.$extension;
            $data = $request->file('cover')->storeAs('img', $newName);
        };

        $validator['cover'] = $data;

        Book::create($validator);
        Alert::success('Berhasil Menambahkan Buku');
        return redirect('books');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(Book $book)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = Book::findOrFail($id);
        $category = Category::all();

        return view('admin.books.edit' ,compact('book', 'category'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = $request->validate([
            'isbn' => 'required',
            'judul_buku' => 'required',
            'penerbit' => 'required',
            'sinopsis' => 'required',
            'keterangan' => 'required',
            'category_id' => 'required',
            'stock' => 'required'
        ]);
        
        $book = Book::findOrFail($id);
        
        $newName = '';
        $data = '';
        if($request->hasFile('cover')){
            $request->validate([
                'cover' => 'required|image|max:10000|mimes:jpg'
            ]);
            Storage::delete($book->cover);
            $cover = $request->cover;
            $extension = $request->file('cover')->getClientOriginalExtension();
            $newName = $request->isbn.'-'.now()->timestamp.'.'.$extension;
            $data = $request->file('cover')->storeAs('img', $newName);
            $validator['cover'] = $data;
            $book->update($validator);
            Alert::success('Berhasil Update Buku');
        } else {
            $book->update([
                'isbn' => $request->isbn,
                'judul_buku' => $request->judul_buku,
                'penerbit' => $request->penerbit,
                'sinopsis' => $request->sinopsis,
                'keterangan' => $request->keterangan,
                'category_id' => $request->category_id,
                'stock' => $request->stock,
                'cover' => $book->cover
            ]);
        }
        

       
        Alert::success('Berhasil Update Buku');        
        return redirect('books');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = Book::findOrFail($id);
        if(Storage::delete($book->cover)){
            Storage::delete($book->cover);
        }
        $book->delete();
        Alert::success('Berhasil Menghapus Buku');
        return redirect('books');
    }

    public function hide($id)
    {
        $book = Book::findorFail($id);
        if($book->tampil == 1){
            $book->update([
                'tampil' => 0
            ]);
        } else {
            $book->update([
                'tampil' => 1
            ]);
        }
        return redirect('books');
    }
}

ModernLibrary/resources/views/admin/books/edit.blade.php
@extends('layouts.template')

@section('title', 'Edit buku')

@section('content')
    <form action="/books/{{ $book->id }} " method="POST" enctype="multipart/form-data">
        @csrf
        @method('put')
        <div class="container-xxl flex-grow-1 container-p-y">
            <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Data /</span> <span
                    class="text-muted fw-light">Kelola Buku /</span> Edit Jenis Buku</h4>

            <div class="col-xxl">
                <div class="card mb-4">
                    <div class="card-body">
                        <form action="{{ route('books.update', $book->id) }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="form-group mb-3">
                                <label>ISBN</label>
                                <input type="text" class="form-control" value="{{ $book->isbn }} " name="isbn"
                                    placeholder="Masukan isbn">
                                @error('isbn')
                                    <div class="alert alert-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                            <div class="form-group mb-3">
                                <label>Judul Buku</label>
                                <input type="text" class="form-control" value="{{ $book->judul_buku }}" name="judul_buku"
                                    placeholder="Masukan Title">
                                @error('judul_buku')
                                    <div class="alert alert-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                            <div class="form-group mb-3">
                                <label>Penerbit</label>
                                <input type="text" class="form-control" value="{{ $book->penerbit }}" name="penerbit"
                                    placeholder="Masukan Penerbit">
                                @error('penerbit')
                                    <div class="alert alert-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                            <div class="form-group mb-3">
                                <label>Sinopsis</label>
                                <input type="text" class="form-control"value="{{ $book->sinopsis }}" name="sinopsis"
                                    placeholder="Masukan Sinopsis">
                                @error('sinopsis')
                                    <div class="alert alert-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                            <div class="form-group mb-3">
                                <label>Keterangan</label>
                                <input type="text" class="form-control" value="{{ $book->keterangan }}"name="keterangan"
                                    placeholder="Masukan Keterangan">
                                @error('keterangan')
                                    <div class="alert alert-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <div class="form-group mb-3">
                                <label>Stock</label>
                                <input type="text" class="form-control" value="{{ $book->stock }}" name="stock"
                                    placeholder="Masukan Stock">
                                @error('stock')
                                    <div class="alert alert-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                            <div class="form-group mb-3">
                                <label>Category</label>
                                <select name="category_id" class="form-select" id="exampleFormControlSelect1">
                                    @foreach ($category as $data)
                                        <option value="{{ $data->id }}" @selected($book->category_id == $data->id)>
                                            {{ $data->nama_kategori }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group mb-3">
                                <label>Cover</label>
                                <input type="file" class="form-control" name="cover">
                                @error('cover')
                                    <div class="alert alert-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                            <div class="form-group mb-3">
                                <label class="form-label">Cover Sebelumnya : </label>
                            </div>
                            <div class=" form-group mb-3">
                                <img src="{{ asset('storage/' . $book->cover) }}" width="200px" alt="">
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <div class="row justify-content-end">
                                {{-- <div class="col-sm-15"> --}}
                                {{-- </div> --}}
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

ModernLibrary/resources/views/admin/books/tambah.blade.php
@extends('layouts.template')

@section('title', 'Tambah buku')

@section('content')
<form action="/books" method="POST" enctype="multipart/form-data">
@csrf
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Data /</span> <span class="text-muted fw-light">Kelola Buku /</span> Tambah Jenis Buku</h4>

    <div class="col-xxl">
        <div class="card mb-4">
            <div class="card-body">
            <div class="form-group mb-3">
                <label>ISBN</label>
                <input type="text" class="form-control" name="isbn" placeholder="Masukan isbn">
                @error('isbn')
                    <div class="alert alert-danger">
                        {{$message}}
                    </div>
                @enderror
            </div>
            <div class="form-group mb-3">
                <label>Judul Buku</label>
                <input type="text" class="form-control" name="judul_buku" placeholder="Masukan Title">
                @error('judul_buku')
                    <div class="alert alert-danger">
                        {{$message}}
                    </div>
                @enderror
            </div>
            <div class="form-group mb-3">
                <label>Penerbit</label>
                <input type="text" class="form-control" name="penerbit" placeholder="Masukan Penerbit">
                @error('penerbit')
                    <div class="alert alert-danger">
                        {{$message}}
                    </div>
                @enderror
            </div>
            <div class="form-group mb-3">
                <label>Sinopsis</label>
                <input type="text" class="form-control" name="sinopsis" placeholder="Masukan Sinopsis">
                @error('sinopsis')
                    <div class="alert alert-danger">
                        {{$message}}
                    </div>
                @enderror
            </div>
            <div class="form-group mb-3">
                <label>Keterangan</label>
                <input type="text" class="form-control" name="keterangan" placeholder="Masukan Keterangan">
                @error('keterangan')
                    <div class="alert alert-danger">
                        {{$message}}
                    </div>
                @enderror
            </div>
            <div class="form-group mb-3">
                <label>Cover</label>
                <input type="file" class="form-control" name="cover">
                @error('cover')
                    <div class="alert alert-danger">
                        {{$message}}
                    </div>
                @enderror
            </div>
            <div class="form-group mb-3">
                <label>Stock</label>
                <input type="text" class="form-control" name="stock" placeholder="Masukan Stock">
                @error('stock')
                    <div class="alert alert-danger">
                        {{$message}}
                    </div>
                @enderror
            </div>
            <div class="form-group mb-3">
                <label>Kategori</label>
                <select name="category_id" class="form-control" id="">
                    <option value="">--Pilih Category--</option>
                    @forelse ($category as $item)
                    <option value="{{$item->id}}">{{$item->nama_kategori}} </option>
                    @empty
                    <option value="">Tidak ada Data di table Category</option>
                    @endforelse
                </select>
                {{-- @error('category_id')
                    <div class="alert alert-danger">
                        {{$message}}
                    </div>
                @enderror --}}
            </div>
            
            <button type="submit" class="btn btn-primary">Submit</button>
            <div class="row justify-content-end">
               {{-- <div class="col-sm-15"> --}}
                {{-- </div> --}}
            </div>
        </div>
        </div>
    </div>
</div>
</form>
@endsection

ModernLibrary/resources/views/admin/books/tampil.blade.php
@extends('layouts.template')

@section('title', 'Data Kategori')
@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Data /</span> Kelola Kategori</h4>

    <!-- Basic Bootstrap Table -->
    <div class="card">
        <h5 class="card-header">Kelola Kategori Buku</h5>
        <div class="table-responsive">
            <a href="{{ route('books.create') }}" class="btn btn-primary ms-3">Tambah Data</a>
            <table class="table" id="myTable">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>ISBN</th>
                        <th>Judul Buku</th>
                        <th>Penerbit</th>
                        <th>Sinopsis</th>
                        <th>Keterangan</th>
                        <th>Kategori</th>
                        <th>Stok</th>
                        <th>Cover</th>
                        <th>Aksi</th>

                    </tr>
                </thead>
                <tbody class="table-border-bottom-0">
                    @foreach ($book as $item)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $item->isbn }}</td>
                        <td>{{ $item->judul_buku }}</td>
                        <td>{{ $item->penerbit }}</td>
                        <td>{{ $item->sinopsis }}</td>
                        <td>{{ $item->keterangan }}</td>
                        <td>{{ $item->category->nama_kategori }}</td>
                        <td>{{ $item->stock }}</td>
                        <td><img src="{{ asset('storage/' . $item->cover) }}" alt="" width="100px"></td>
                        <td class="d-flex">
                                    <a class="btn btn-warning" href="{{ route('books.edit', $item->id) }}"><i class="bx bx-edit-alt me-1"></i></a>
                                    <form action="{{ route('books.destroy', $item -> id) }}" method="POST" id="myForm">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-danger ms-3" onclick="return confirm('Yakin hapus Data ?')"><i class="bx bx-trash me-1"></i></button>
                                    </form>
                                    @if (Auth::user()->role == "admin")
                                @if ($item->tampil == 1)
                                    <a href="/tampil/{{ $item->id }}" class="btn btn-primary ms-3">Sembunyi</a>
                                @else
                                    <a href="/tampil/{{ $item->id }}" class="btn btn-warning ms-3">Tampil</a>
                                @endif
                            @endif
                                
                        </td>
                       
                    </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>

@endsection